spring.application.name=neobank
# Configuracion de la conexion a MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/neobank?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=DB117
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuracion de JPA-Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

# CONFIGURACION DE APACHE KAFKA
# Dinde esta el servidor de Kafka cuando programamos en local
spring.kafka.bootstrap-servers=localhost:9092

# Como traducimos la llave (Key) del mensaje? A simple texto
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer

# Como traducimos el cuerpo (Value) del mensaje A formato JSON
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

